### ISSUE TITLE
Unable to open vscode project

### ISSUE THREAD

**Issue by ygini** [airsports-no/airsportslivetracking#7]
Hello

I'm trying to work with the vscode setup present in the repository now and I cannot open the devcontainer, it fail with the following error:

```
 => ERROR [tracker_daphne tracker_base 17/31] RUN pip install /pyeval7     0.5s
------
 > [tracker_daphne tracker_base 17/31] RUN pip install /pyeval7:
0.336 ERROR: Directory '/pyeval7' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
------
failed to solve: process "/bin/sh -c pip install /pyeval7" did not complete successfully: exit code: 1
[694112 ms] Error: Command failed: docker-compose --project-name airsportslivetracking -f /Users/ygi/Sources/Contrib/airsportslivetracking/docker-compose.yml -f /Users/ygi/Sources/Contrib/airsportslivetracking/.devcontainer/docker-compose.yml -f /Users/ygi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1708754426923.yml build
[694113 ms]     at pw (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:429:525)
[694113 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[694113 ms]     at async L$ (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:429:2496)
[694113 ms]     at async N$ (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:409:3165)
[694113 ms]     at async tAA (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:3833)
[694113 ms]     at async CC (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:481:4775)
[694113 ms]     at async NeA (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:11107)
[694113 ms]     at async MeA (/Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js:614:10848)
[694117 ms] Exit code 1
[694119 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/ygi/.vscode/extensions/ms-vscode-remote.remote-containers-0.338.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/ygi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-8430f7d0-89a2-4545-bf44-bf4954f62ba01708754423880 --workspace-folder /Users/ygi/Sources/Contrib/airsportslivetracking --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/ygi/Sources/Contrib/airsportslivetracking --id-label devcontainer.config_file=/Users/ygi/Sources/Contrib/airsportslivetracking/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/ygi/Sources/Contrib/airsportslivetracking/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[694119 ms] Exit code 1
```

Also, the devcontainer is really long to open. Maybe an evolution could be to propose an initial container with all requirements already installed as a side project here, published publicly on GH Registry, and rebuilt every weekend using GH Actions. Basically the tracker_base you already have, but updated quite often and used as a source for the Dockerfile in the project.

Like that when we open vscode, it's fast, and we are sure that everyone run the same development containers with the same libs versions.

The same error happen with a simple `docker compose build` at the root of the project.

**Comment by ygini** [comment]
OK the issue actually come from a third part library not downloaded inside the Dockerfile but sideloaded as a git submodule.
